### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by choweiyuan** [cdancy/jenkins-rest#142]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

JFrog is sunsetting JCenter bintray, which this repository is using. Should move to other repositories such as maven central.

### Expected Behavior

Users should be able to use this library via maven central

### Current Behavior

Users have to specify jcenter in mvn/gradle repo definition

**Comment by cdancy** [comment]
@choweiyuan thanks for opening the ISSUE to track things. Yes I heard about this over the past week. I generally shy away from publishing directly to maven as it's just a pain to do and feels overly complicated. I'm hoping that gradle themselves will jump behind a potential solution. I hear github has their own package repository, which I've never played with, but could be a good solution. 

I'm definitely open for suggestions as to where the greater community is heading.

**Comment by choweiyuan** [comment]
I haven't read this article but seems to have a lot of helpful guide on how to migrate

https://blog.sonatype.com/what-publishers-need-to-know-about-migrating-from-jcenter-/-bintray-to-the-central-repository

More URLs
https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/
https://github.com/vanniktech/gradle-maven-publish-plugin

**Comment by martinda** [comment]
@cdancy : You need to pick coordinates for Maven Central. There are two choices, and proof of ownership have to be made in either case. As much as I'd like to, I can't really do this for the project.

Please see [Choosing your coordinates](https://central.sonatype.org/publish/requirements/coordinates/) and this [blog post](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/) explaining the process step by step.

**Comment by martinda** [comment]
@cdancy It turns out that you do not own the cdancy.com domain (it is owned by a university professor). So publishing on Maven central using com.cdancy will not be possible. I registered myself to central and did a SNAPSHOT release under [ca.martinda](https://s01.oss.sonatype.org/#nexus-search;quick~jenkins-rest). Direct link: https://s01.oss.sonatype.org/content/repositories/snapshots/ca/martinda/jenkins-rest/

Would you prefer a different domain? I am sure we can come up with a nice domain name.

**Comment by martinda** [comment]
FYI I am slowly getting there... In order to get an unowned and "neutral" domain name for publishing, I had to fork the project over to a new github organization: https://github.com/jrestclients/jenkins-rest

In turn, this github org was used to publish a snapshot to maven central: https://s01.oss.sonatype.org/index.html#nexus-search;quick~io.github.jrestclients from my local clone.

My next steps are to understand how to get it to show up in the maven central search and setup github actions.

See https://github.com/jrestclients/jenkins-rest/pull/1

**Comment by choweiyuan** [comment]
I see that this is closed but not sure if it is published to maven central at the moment? What's the status of this?

**Comment by cdancy** [comment]
@choweiyuan it is indeed being published to maven central now. Check out the README to see newest GAV coordinates.

Martin opened up that project as I was dragging my feet with migrating things to maven central. I will let him give an update as to the state of things there and what he wants to do with that project. I plan on maintaining things here however now that things are properly working.
