### ISSUE TITLE
jobsApi().buildInfo().result() bug??

### ISSUE THREAD

**Issue by ksshim86** [cdancy/jenkins-rest#227]
I'm not good at English. hope you understand.

SUCCESS is returned even though the build is not finished.

The part where SUCCESS is returned is sshCommand.

Shouldn't the test function "getCompleteBuild" be changed to "buildInfo.building() == true" ?

**Comment by cdancy** [comment]
@ksshim86 are you executing tests or this is a real world scenario? Can paste a snippet of code you are using to reproduce the issue?

**Comment by ksshim86** [comment]
"buildInfo.result()" is called "sshCommand" and "SUCCESS" is returned.

```java
private BuildInfo getCompletedBuild(String jobName, QueueItem queueItem) throws InterruptedException {
    BuildInfo buildInfo = api.jobsApi().buildInfo(PIPELINE_PATH, jobName, queueItem.executable().number());
    ProgressiveText pt = null;

    while (buildInfo.building() == true) {
        Thread.sleep(2000);
        pt = client.api().jobsApi().progressiveText(PIPELINE_PATH, jobName, queueItem.executable().number(), 0);
        System.out.println(pt.text());

        buildInfo = api.jobsApi().buildInfo(PIPELINE_PATH, jobName, queueItem.executable().number());
    }

    return buildInfo;
}
```

```javascript
// jenkins pipeline

stage('Publish') {
    steps {
        script {
            if("${publish_yn}" == "YES") {
                sshPublisherByProp('dev_was #1', WAS_WAR_FULL_NM);
            }
        }
    }
}
stage('Deploy') {
    steps {
        script {
            if("${deploy_yn}" == "YES") {
                sshCommand remote: 
                    wasRemote, 
                command:
                    "cd " + env.WEBROOTS_PATH + ";" +
                    "tar -zcf " + env.BACKUP_PATH + PROJECT_PATH + WAS_WAR_NM + "-${buildVersion}" + ".tar.gz " + PROJECT_PATH + ";" +
                    "rm -rf " + env.SOURCE_PATH + PROJECT_PATH + "*;" +
                    "mv " + env.SOURCE_PATH + WAS_WAR_FULL_NM + " " + env.SOURCE_PATH + PROJECT_PATH + ";" +
                    "cd " + env.SOURCE_PATH + PROJECT_PATH + ";" +
                    "jar -xf " + WAS_WAR_FULL_NM + ";" + 
                    "rm -rf " + WAS_WAR_FULL_NM + ";" +
                    "rsync -avr --delete " + env.SOURCE_PATH + PROJECT_PATH + " " + env.WEBROOTS_PATH + PROJECT_PATH + ";"
                
                sshCommand remote: 
                    wasRemote, 
                command: 
                    "find " + env.BACKUP_PATH + PROJECT_PATH + " -mtime +10 -exec rm -f {} \\;"

                def result11 = serverRestart(WAS_REMOTE, "restful11")

                if (result11.indexOf("STANDBY") >= 0) {
                    error "SERVER RESTART FAILED"
                }
            }
        }
    }
}
```

**Comment by martinda** [comment]
Hello @ksshim86 I have no evidence, but I suspect the test code is okay. However in your code maybe the build result is set to non-null before the build ends. Maybe the `sshCommand` does that internally? I do not know.

I remember that it is complicated to detect the end of the build. I vaguely remember that if I look at `buildInfo.building()` too soon after the build transitions from "in the queue" and "building", the `buildInfo.building()` method still returns `false` and I falsely detect that the build has ended. But in reality, the build has barely started building. I think that is why the test code looks at `buildInfo.result()`. In the test, looking at `buildInfo.result()` works because the test does not set the build result until later. In your application, you may have to look at both the `result()` and the `building()` value. I hope this helps.

**Comment by ksshim86** [comment]
@martinda thank you. Let's test it a little more variety.
