### ISSUE TITLE
Consider upgrade gson version to 2.9.0+

### ISSUE THREAD

**Issue by wahcen** [cdancy/jenkins-rest#295]
### Expected Behavior
It shouldn't throw an NoSuchMethodError

### Current Behavior
Failed to build JenkinsClient and it throwed an NoSuchMethodError at line 99 in GsonModule.class with message: 
"NoSuchMethodError: 'void ConstructorConstructor.<init>(Map)'".

### Context
It's clearly that gson v2.9.0 has refactored com.google.gson.internal.ConstructorConstructor class constructor method, thus
i have to downgrade my gson version to 2.8.9, and i was wondering why this library is using google gson's internal classes?

### Steps to Reproduce (for bugs)
Just add gson 2.9.0 in pom.xml, and JenkinsClient.build() will fail.
```xml
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.9.0</version>
</dependency>
```

### Your Environment
gson 2.8.9

**Comment by cdancy** [comment]
@wahcen if you use the `all` classifier does that get you further? That should bundle all of our dependencies into a single jar and help you move forward.

We're just using OOTB gson for json-to-object marshalling. Nothing special. You're most likely hitting a clobbering issue on the classpath due to conflicting gson classes. Using the `all` classifier as I said should solve this problem for you.

**Comment by wahcen** [comment]
@cdancy Yes, it took effect, thank u for helping.
